"""DAGR MCP Sprint A1 — multi-binding behavioral freeze.

This module characterizes and freezes the *observable* behavior of the existing
external FastMCP binding before any neutral lifecycle contract or core extraction
begins. It captures behavior; it does not refactor it. The current repository
bytes are the oracle. No neutral core is invented, no implementation file moves,
no public interface is renamed, and no receipt semantics, projection identifiers,
golden digests, or signing bytes are changed.

Each section below freezes one numbered item from the sprint's freeze list. Items
that require the co-installed ``arcs_verify`` verifier (14, 15) are marked and
skip cleanly when it is absent; every other item is frozen standalone.

Committed fixtures under ``tests/golden/behavioral_freeze/`` are regenerated by
the deterministic recipes in ``tests.behavioral_freeze_recipe`` /
``tests.behavioral_freeze_custody`` and byte-compared here, so any drift in
signing bytes, normalized content, digests, or the public surface fails loudly.
"""

from __future__ import annotations

import base64
import copy
import hashlib
import json
import typing
from pathlib import Path
from typing import Any

import pytest
import rfc8785
from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

from dagr_mcp import (
    fastmcp_binding,
    mcp_record_custody_gateway,
    srs_receipts,
)
from dagr_mcp.srs_receipts import (
    RawEnvelopeFileSink,
    ReceiptContentError,
    ReceiptContext,
    SignedReceiptEmitter,
    fastmcp_tool_result_digest,
    sha256_digest,
)
from dagr_mcp.fastmcp_binding import project_fastmcp_tool_result

from tests.behavioral_freeze_recipe import (
    FREEZE_ADMISSION_ID,
    FREEZE_ISSUED_AT,
    freeze_identity,
    generate_frozen_receipts,
    write_frozen_trust_bundle,
)
from tests.behavioral_freeze_custody import generate_frozen_gateways

ROOT = Path(__file__).resolve().parents[1]
GOLDEN = ROOT / "tests/golden/behavioral_freeze"
SCHEMA_PATH = ROOT / "dagr_mcp/vendor/srs/srs-envelope-v0.2.0.schema.json"
MCP_PROFILE = "srs.mcp.sdk_enforcement.v0.1"

try:  # arcs_verify is co-installed only in the multi-binding lane.
    from arcs_verify.verifier import verify_receipt as _arcs_verify_receipt
except ModuleNotFoundError:  # pragma: no cover - exercised by the standalone lane
    _arcs_verify_receipt = None

requires_arcs = pytest.mark.skipif(
    _arcs_verify_receipt is None,
    reason="arcs_verify not co-installed; ARCS receipt-class proofs skipped",
)

# Fields that are permitted to vary run-to-run (wall clock + UUID) and are pinned
# deterministically in the frozen fixtures. Everything else is exact.
NONDETERMINISTIC_RECEIPT_FIELDS = ("receipt_id", "issued_at", "receipt_signature")


def _decode_b64url(value: str) -> bytes:
    return base64.urlsafe_b64decode(value + "=" * (-len(value) % 4))


def _committed(name: str) -> dict[str, Any]:
    return json.loads((GOLDEN / name).read_text(encoding="utf-8"))


def _committed_receipts() -> dict[str, dict[str, Any]]:
    expectations = _committed("arcs_expectations.json")
    return {
        entry["name"]: _committed(entry["path"])
        for entry in expectations["receipts"]
    }


def _verify_signature(receipt: dict[str, Any], public_key: bytes) -> None:
    preimage = copy.deepcopy(receipt)
    signature = _decode_b64url(preimage["receipt_signature"].pop("signature"))
    Ed25519PublicKey.from_public_bytes(public_key).verify(
        signature, rfc8785.dumps(preimage)
    )


def _content_projection(receipt: dict[str, Any]) -> dict[str, Any]:
    """Equality projection: drop the permitted-nondeterministic fields."""

    projected = copy.deepcopy(receipt)
    for field in NONDETERMINISTIC_RECEIPT_FIELDS:
        projected.pop(field, None)
    return projected


# --------------------------------------------------------------------------- #
# FREEZE ITEM 1 — admission decisions and disposition vocabulary              #
# --------------------------------------------------------------------------- #


def test_freeze_disposition_vocabulary():
    assert typing.get_args(fastmcp_binding.Disposition) == (
        "admitted",
        "refused",
        "deferred_for_review",
    )
    # The tool-class vocabulary the binding admits against is frozen too.
    assert typing.get_args(fastmcp_binding.ToolClass) == (
        "read",
        "write",
        "destructive",
    )


def test_freeze_admission_receipts_carry_frozen_dispositions():
    receipts = _committed_receipts()
    assert receipts["admission-admitted"]["disposition"] == "admitted"
    assert receipts["admission-refused"]["disposition"] == "refused"
    assert receipts["admission-deferred"]["disposition"] == "deferred_for_review"
    # Admission receipts never observe tool resolution.
    for name in ("admission-admitted", "admission-refused", "admission-deferred"):
        assert receipts[name]["tool_resolution_status"] == "not_observed"
        assert receipts[name]["receipt_kind"] == "admission"


# --------------------------------------------------------------------------- #
# FREEZE ITEM 2 — refusal and deferral reason codes                           #
# --------------------------------------------------------------------------- #


def _harness_bridge(tmp_path: Path):
    from dagr_mcp.srs_bridge import BridgeConfig, HarnessSRSBridge

    identity = freeze_identity()
    emitter = SignedReceiptEmitter(identity=identity, sink=RawEnvelopeFileSink(tmp_path))
    bridge = HarnessSRSBridge(
        emitter=emitter,
        config=BridgeConfig(
            runtime_instance_id="runtime:test:1",
            boundary_id="boundary:test:1",
            policy_pack_id="policy:test",
            policy_pack_version="1",
        ),
    )
    return identity, bridge


def _load_admissions(tmp_path: Path) -> list[dict[str, Any]]:
    receipts = [
        json.loads(p.read_text(encoding="utf-8"))
        for p in tmp_path.glob("urn_srs_receipt_*.json")
    ]
    return [r for r in receipts if r["receipt_kind"] == "admission"]


def test_freeze_reason_code_deny(tmp_path):
    from dagr_mcp.enforcement_harness import HarnessConfig, HarnessSinks, ToolPolicy, wrap_handler
    from dagr_mcp.sdk_spine import InMemoryEventSink

    _identity, bridge = _harness_bridge(tmp_path)
    wrapped = wrap_handler(
        lambda *a, **k: {"unexpected": True},
        HarnessConfig("1", "module", "1", "profile", "policy"),
        HarnessSinks(event=InMemoryEventSink()),
        policies=[ToolPolicy("danger", "destructive", "deny")],
        srs_bridge=bridge,
    )
    result = wrapped("danger", {"record_ref": "record:1"}, {"request_ref": "call-deny"})
    assert not result.ok
    admissions = _load_admissions(tmp_path)
    assert len(admissions) == 1
    assert admissions[0]["disposition"] == "refused"
    assert admissions[0]["reason_code"] == "policy_refused"


def test_freeze_reason_code_unknown_tool_fail_closed(tmp_path):
    from dagr_mcp.enforcement_harness import HarnessConfig, HarnessSinks, wrap_handler
    from dagr_mcp.sdk_spine import InMemoryEventSink

    _identity, bridge = _harness_bridge(tmp_path)
    wrapped = wrap_handler(
        lambda *a, **k: {"unexpected": True},
        HarnessConfig("1", "module", "1", "profile", "policy"),
        HarnessSinks(event=InMemoryEventSink()),
        policies=[],  # unknown tool -> fail closed
        srs_bridge=bridge,
    )
    result = wrapped("mystery", {"record_ref": "record:1"}, {"request_ref": "call-unknown"})
    assert not result.ok
    admissions = _load_admissions(tmp_path)
    assert len(admissions) == 1
    assert admissions[0]["disposition"] == "refused"
    assert admissions[0]["reason_code"] == "unknown_tool_fail_closed"


def test_freeze_deferral_reason_and_retry_contract(tmp_path):
    from dagr_mcp.enforcement_harness import HarnessConfig, HarnessSinks, ToolPolicy, wrap_handler
    from dagr_mcp.sdk_spine import InMemoryEventSink, InMemoryReviewObjectSink

    _identity, bridge = _harness_bridge(tmp_path)
    wrapped = wrap_handler(
        lambda *a, **k: {"unexpected": True},
        HarnessConfig("1", "module", "1", "profile", "policy"),
        HarnessSinks(event=InMemoryEventSink(), review=InMemoryReviewObjectSink()),
        policies=[ToolPolicy("write", "write", "gate", review_required=True)],
        srs_bridge=bridge,
    )
    result = wrapped("write", {"record_ref": "record:1"}, {"request_ref": "call-gate"})
    assert not result.ok
    admissions = _load_admissions(tmp_path)
    assert len(admissions) == 1
    assert admissions[0]["disposition"] == "deferred_for_review"
    assert admissions[0]["retry_contract"] == "retry_after_approval"
    assert admissions[0]["review_object_ref"]


def test_freeze_gate_without_review_sink_reason_code(tmp_path):
    from dagr_mcp.enforcement_harness import HarnessConfig, HarnessSinks, ToolPolicy, wrap_handler
    from dagr_mcp.sdk_spine import InMemoryEventSink

    _identity, bridge = _harness_bridge(tmp_path)
    wrapped = wrap_handler(
        lambda *a, **k: {"unexpected": True},
        HarnessConfig("1", "module", "1", "profile", "policy"),
        HarnessSinks(event=InMemoryEventSink()),  # no review sink
        policies=[ToolPolicy("write", "write", "gate", review_required=True)],
        srs_bridge=bridge,
    )
    result = wrapped("write", {"record_ref": "record:1"}, {"request_ref": "call-nogate"})
    assert not result.ok
    # A review-required gate makes the review sink an *effective required sink*, so
    # its absence is caught by the required-sink health check before _gate_call
    # runs: the frozen failure_reason is review_object_sink_unavailable and the
    # emitted refusal reason_code is required_sink_unavailable.
    assert result.failure_reason == "review_object_sink_unavailable"
    admissions = _load_admissions(tmp_path)
    assert len(admissions) == 1
    assert admissions[0]["disposition"] == "refused"
    assert admissions[0]["reason_code"] == "required_sink_unavailable"


# --------------------------------------------------------------------------- #
# FREEZE ITEM 3 — receipt cardinality and ordering                            #
# --------------------------------------------------------------------------- #


def test_freeze_admitted_call_emits_two_receipts_admission_then_outcome(tmp_path):
    from dagr_mcp.enforcement_harness import HarnessConfig, HarnessSinks, ToolPolicy, wrap_handler
    from dagr_mcp.sdk_spine import InMemoryEventSink

    identity, bridge = _harness_bridge(tmp_path)
    seen_at_inner = {"count": None}

    def inner(tool_name, arguments, context=None):
        seen_at_inner["count"] = len(list(tmp_path.glob("urn_srs_receipt_*.json")))
        return {"ok": True}

    wrapped = wrap_handler(
        inner,
        HarnessConfig("1", "module", "1", "profile", "policy"),
        HarnessSinks(event=InMemoryEventSink()),
        policies=[ToolPolicy("records.lookup", "read", "allow")],
        srs_bridge=bridge,
    )
    result = wrapped("records.lookup", {"record_ref": "record:1"}, {"request_ref": "call-1"})
    assert result.ok
    # Exactly one admission receipt exists on disk before the outcome is written.
    assert seen_at_inner["count"] == 1
    receipts = [json.loads(p.read_text()) for p in tmp_path.glob("urn_srs_receipt_*.json")]
    assert len(receipts) == 2
    kinds = sorted(r["receipt_kind"] for r in receipts)
    assert kinds == ["admission", "outcome"]


def test_freeze_terminal_refusal_emits_single_receipt(tmp_path):
    from dagr_mcp.enforcement_harness import HarnessConfig, HarnessSinks, ToolPolicy, wrap_handler
    from dagr_mcp.sdk_spine import InMemoryEventSink

    _identity, bridge = _harness_bridge(tmp_path)
    ran = {"inner": False}

    def inner(*a, **k):
        ran["inner"] = True
        return {}

    wrapped = wrap_handler(
        inner,
        HarnessConfig("1", "module", "1", "profile", "policy"),
        HarnessSinks(event=InMemoryEventSink()),
        policies=[ToolPolicy("danger", "destructive", "deny")],
        srs_bridge=bridge,
    )
    result = wrapped("danger", {"record_ref": "record:1"}, {"request_ref": "call-2"})
    assert not result.ok
    assert not ran["inner"]
    receipts = list(tmp_path.glob("urn_srs_receipt_*.json"))
    assert len(receipts) == 1


# --------------------------------------------------------------------------- #
# FREEZE ITEM 4 — admission-to-outcome parent/reference relationships         #
# --------------------------------------------------------------------------- #


def test_freeze_every_outcome_references_the_admission_receipt():
    receipts = _committed_receipts()
    for name in (
        "outcome-result-returned",
        "outcome-error-returned",
        "outcome-exception",
        "outcome-task-submitted",
        "outcome-indeterminate",
    ):
        assert receipts[name]["admission_receipt_ref"] == FREEZE_ADMISSION_ID
        assert receipts[name]["receipt_kind"] == "outcome"
    assert receipts["admission-admitted"]["receipt_id"] == FREEZE_ADMISSION_ID


def test_freeze_bridge_result_outcome_links_to_admission(tmp_path):
    from dagr_mcp.enforcement_harness import HarnessConfig, HarnessSinks, ToolPolicy, wrap_handler
    from dagr_mcp.sdk_spine import InMemoryEventSink

    _identity, bridge = _harness_bridge(tmp_path)
    wrapped = wrap_handler(
        lambda *a, **k: {"record_ref": "record:1"},
        HarnessConfig("1", "module", "1", "profile", "policy"),
        HarnessSinks(event=InMemoryEventSink()),
        policies=[ToolPolicy("records.lookup", "read", "allow")],
        srs_bridge=bridge,
    )
    wrapped("records.lookup", {"record_ref": "record:1"}, {"request_ref": "call-1"})
    receipts = [json.loads(p.read_text()) for p in tmp_path.glob("urn_srs_receipt_*.json")]
    admission = next(r for r in receipts if r["receipt_kind"] == "admission")
    outcome = next(r for r in receipts if r["receipt_kind"] == "outcome")
    assert outcome["admission_receipt_ref"] == admission["receipt_id"]


# --------------------------------------------------------------------------- #
# FREEZE ITEM 5 — normalized unsigned receipt content                         #
# FREEZE ITEM 6 — deterministic signing behavior                              #
# --------------------------------------------------------------------------- #


def test_freeze_receipts_are_byte_stable_and_match_committed_golden(tmp_path):
    """Regenerating with the frozen recipe reproduces the committed bytes exactly."""

    regenerated = generate_frozen_receipts(tmp_path)
    for fr in regenerated:
        committed_bytes = (GOLDEN / fr.filename).read_bytes()
        actual_bytes = (tmp_path / fr.filename).read_bytes()
        assert actual_bytes == committed_bytes, fr.name


def test_freeze_signatures_verify_under_the_frozen_identity():
    public_key = freeze_identity().public_key_bytes()
    for receipt in _committed_receipts().values():
        _verify_signature(receipt, public_key)


def test_freeze_signature_covers_every_field():
    """Any single-field mutation invalidates the deterministic signature."""

    public_key = freeze_identity().public_key_bytes()
    receipt = _committed_receipts()["outcome-indeterminate"]
    _verify_signature(receipt, public_key)

    for field, mutate in (
        ("outcome", lambda r: r.__setitem__("outcome", "result_returned")),
        ("delivery_incomplete", lambda r: r.__setitem__("delivery_incomplete", False)),
        ("admission_receipt_ref", lambda r: r.__setitem__("admission_receipt_ref", "urn:tamper")),
    ):
        tampered = copy.deepcopy(receipt)
        mutate(tampered)
        with pytest.raises(InvalidSignature):
            _verify_signature(tampered, public_key)


def test_freeze_permitted_nondeterministic_fields_are_pinned():
    """receipt_id and issued_at are the only non-signature volatile fields, pinned."""

    receipts = _committed_receipts()
    for receipt in receipts.values():
        assert receipt["issued_at"] == FREEZE_ISSUED_AT
        assert receipt["receipt_id"].startswith("urn:srs:receipt:")


def test_freeze_unsigned_content_projection_is_stable_across_real_clock_and_uuid(tmp_path):
    """Equality projection: with a live UUID + clock, everything but the pinned
    volatile fields still matches the frozen admission content byte-for-byte."""

    identity = freeze_identity()
    emitter = SignedReceiptEmitter(identity=identity, sink=RawEnvelopeFileSink(tmp_path))
    # No id/clock factories -> real uuid4 + wall-clock issued_at.
    receipt_id = emitter.emit_admission(
        context=ReceiptContext(
            runtime_instance_id="runtime:freeze:1",
            boundary_id="boundary:freeze:1",
            policy_pack_id="policy:freeze",
            policy_pack_version="1",
            subject_ref="subject:freeze:1",
            logical_call_id="call:freeze:admitted",
            actor_ref="actor:freeze:1",
            binding_version="fastmcp.middleware.v0.1",
        ),
        requested_tool_name="records.lookup",
        argument_digest="sha256:" + "a" * 64,
        disposition="admitted",
        additional_attestation_limits=(
            "The middleware is installed once at the institutional trust boundary; "
            "receipts attest only to observations at that boundary.",
        ),
    )
    live = next(
        json.loads(p.read_text())
        for p in tmp_path.glob("urn_srs_receipt_*.json")
        if json.loads(p.read_text())["receipt_id"] == receipt_id
    )
    committed = _committed_receipts()["admission-admitted"]
    assert _content_projection(live) == _content_projection(committed)
    # And the volatile fields genuinely varied from the pinned fixture values.
    assert live["receipt_id"] != committed["receipt_id"]


# --------------------------------------------------------------------------- #
# FREEZE ITEM 7 — result / error / exception / timeout / cancellation / task  #
# --------------------------------------------------------------------------- #


def test_freeze_outcome_vocabulary_and_attestation_limits():
    receipts = _committed_receipts()

    # result_returned / error_returned carry the RESULT_LIMIT and a result_digest.
    for name, outcome in (
        ("outcome-result-returned", "result_returned"),
        ("outcome-error-returned", "error_returned"),
    ):
        r = receipts[name]
        assert r["outcome"] == outcome
        assert r["result_digest"].startswith("sha256:")
        assert srs_receipts.RESULT_LIMIT in r["attestation_limits"]

    # task_submitted carries the TASK_LIMIT.
    task = receipts["outcome-task-submitted"]
    assert task["outcome"] == "task_submitted"
    assert srs_receipts.TASK_LIMIT in task["attestation_limits"]

    # exception carries the exception class in the mcp extension, no result_digest.
    exc = receipts["outcome-exception"]
    assert exc["outcome"] == "exception"
    assert exc["extensions"]["mcp"]["exception_class"] == "TimeoutError"
    assert "result_digest" not in exc

    # indeterminate is the cancellation/timeout outcome.
    indet = receipts["outcome-indeterminate"]
    assert indet["outcome"] == "indeterminate"
    assert "result_digest" not in indet


def test_freeze_binding_maps_cancellation_to_indeterminate_with_governance_fields():
    """The middleware source maps asyncio.CancelledError to the frozen shape."""

    import inspect

    source = inspect.getsource(fastmcp_binding.DAGRMiddleware.on_call_tool)
    assert "asyncio.CancelledError" in source
    assert 'outcome="indeterminate"' in source
    assert '"request_cancelled": True' in source
    assert '"execution_state_unknown": True' in source
    assert '"delivery_incomplete": True' in source
    # An inner exception maps to the exception outcome with the class name.
    assert 'outcome="exception"' in source
    assert "exception_class=type(exc).__name__" in source


# --------------------------------------------------------------------------- #
# FREEZE ITEM 8 — cancellation governance fields                              #
# --------------------------------------------------------------------------- #


def test_freeze_cancellation_field_registry():
    assert srs_receipts.CANCELLATION_FIELD_NAMES == frozenset(
        {"request_cancelled", "execution_state_unknown", "delivery_incomplete"}
    )
    # The A0 rename holds: no result-shaped token survives in the registry.
    assert "result_not_delivered" not in srs_receipts.CANCELLATION_FIELD_NAMES
    assert not any("result" in n for n in srs_receipts.CANCELLATION_FIELD_NAMES)


def test_freeze_cancellation_fields_present_only_on_indeterminate():
    receipts = _committed_receipts()
    indet = receipts["outcome-indeterminate"]
    for field in srs_receipts.CANCELLATION_FIELD_NAMES:
        assert indet[field] is True
    # No other emitted receipt carries any cancellation field.
    for name, receipt in receipts.items():
        if name == "outcome-indeterminate":
            continue
        for field in srs_receipts.CANCELLATION_FIELD_NAMES:
            assert field not in receipt, (name, field)


def test_freeze_cancellation_fields_are_boolean_only_and_indeterminate_only(tmp_path):
    identity = freeze_identity()
    emitter = SignedReceiptEmitter(identity=identity, sink=RawEnvelopeFileSink(tmp_path))
    base = dict(
        runtime_instance_id="r", boundary_id="b", policy_pack_id="p",
        policy_pack_version="1", subject_ref="s", logical_call_id="c",
        actor_ref="a", binding_version="fastmcp.middleware.v0.1",
    )

    # Non-indeterminate outcome rejects any cancellation field.
    with pytest.raises(ReceiptContentError, match="only on indeterminate"):
        emitter.emit_outcome(
            context=ReceiptContext(**base),
            admission_receipt_ref="urn:srs:receipt:admission:1",
            outcome="result_returned",
            result_digest="sha256:" + "e" * 64,
            binding_owned_fields={"request_cancelled": True},
        )
    # Non-boolean cancellation value is refused before signing.
    with pytest.raises(ReceiptContentError, match="must be boolean"):
        emitter.emit_outcome(
            context=ReceiptContext(**base),
            admission_receipt_ref="urn:srs:receipt:admission:1",
            outcome="indeterminate",
            binding_owned_fields={"delivery_incomplete": "leaked rows"},
        )
    # Unknown binding-owned field is refused.
    with pytest.raises(ReceiptContentError, match="unknown binding-owned field"):
        emitter.emit_outcome(
            context=ReceiptContext(**base),
            admission_receipt_ref="urn:srs:receipt:admission:1",
            outcome="indeterminate",
            binding_owned_fields={"result_summary": True},
        )
    assert not list(tmp_path.glob("urn_srs_receipt_*.json"))


# --------------------------------------------------------------------------- #
# FREEZE ITEM 9 — custody observations and attestation limits                 #
# --------------------------------------------------------------------------- #


def test_freeze_custody_status_vocabulary():
    assert [s.value for s in mcp_record_custody_gateway.GatewayCustodyStatus] == [
        "custody_record_ready",
        "custody_record_partial",
        "trace_only",
        "unsupported_boundary_type",
        "missing_actor_context",
        "missing_target_context",
        "privacy_blocked",
        "policy_refused",
        "needs_review",
    ]
    assert [b.value for b in mcp_record_custody_gateway.GatewayBoundaryType] == [
        "mcp_tool_call",
        "mcp_resource_read",
        "mcp_prompt_retrieval",
        "agent_delegation",
    ]
    assert [f.value for f in mcp_record_custody_gateway.GatewayReceiptFamily] == [
        "connection",
        "provenance",
        "sdk_enforcement",
    ]
    assert mcp_record_custody_gateway.AGENT_DELEGATION_BODY_KINDS == frozenset(
        {"agent_delegation_issued", "agent_delegation_revoked"}
    )


def test_freeze_custody_projections_match_committed_golden():
    committed = _committed("custody_projections.json")
    regenerated = {g.name: g.body for g in generate_frozen_gateways()}
    assert regenerated == committed


def test_freeze_custody_gateway_hash_is_deterministic():
    committed = _committed("custody_projections.json")
    for name, body in committed.items():
        assert body["gateway_hash"] == mcp_record_custody_gateway.mcp_record_custody_gateway_hash(body), name


def test_freeze_custody_non_claim_and_exclusion_flags():
    """The refs-only projection pins its fail-closed non-claim posture."""

    committed = _committed("custody_projections.json")
    for name, body in committed.items():
        # Exclusion flags are always asserted true.
        assert body["raw_payload_excluded"] is True, name
        assert body["private_path_redacted"] is True, name
        assert body["tool_arguments_excluded"] is True, name
        assert body["credential_secret_excluded"] is True, name
        # Non-claim flags are always false: it never claims admission or authority.
        assert body["record_admission_claimed"] is False, name
        assert body["mcp_protocol_modified"] is False, name
        assert body["mcp_authority_granted"] is False, name
        assert body["model_output_verified"] is False, name
        # It introduces no new receipt family; it names its schema/kind.
        assert body["schema_version"] == "garp.mcp_record_custody_gateway.v0.1"
        assert body["gateway_kind"] == "mcp_record_custody_gateway"


# --------------------------------------------------------------------------- #
# FREEZE ITEM 10 — result and argument digest behavior                        #
# --------------------------------------------------------------------------- #


def test_freeze_argument_digest_is_rfc8785_sha256():
    # sha256_digest canonicalizes with RFC 8785 JCS and prefixes sha256:.
    digest = sha256_digest({"b": 2, "a": 1})
    assert digest == sha256_digest({"a": 1, "b": 2})  # key-order independent
    assert digest.startswith("sha256:")
    assert len(digest) == len("sha256:") + 64


def test_freeze_result_digest_uses_four_member_projection():
    expected = fastmcp_tool_result_digest(
        content=None,
        structured_content={"record_ref": "record:1"},
        meta=None,
        is_error=False,
    )
    # Recompute the exact projection digest independently.
    projection = {
        "content": None,
        "structuredContent": {"record_ref": "record:1"},
        "_meta": None,
        "isError": False,
    }
    assert expected == "sha256:" + hashlib.sha256(rfc8785.dumps(projection)).hexdigest()


# --------------------------------------------------------------------------- #
# FREEZE ITEM 11 — projection identifiers and FastMCP result-digest behavior  #
# --------------------------------------------------------------------------- #

GOLDEN_PROJECTION_DIGEST = (
    "sha256:26380b315cd335987c15079418c54df086c9a8b3dc7642691ab77b19752a26ce"
)


def test_freeze_projection_member_identifiers():
    from fastmcp.tools.base import ToolResult

    result = ToolResult(
        content=["hello"],
        structured_content={"record_ref": "record:1", "found": True},
        meta={"fixture": "freeze"},
    )
    projection = project_fastmcp_tool_result(result)
    assert list(projection.keys()) == ["content", "structuredContent", "_meta", "isError"]


def test_freeze_projection_golden_digest_is_unchanged():
    from fastmcp.tools.base import ToolResult

    result = ToolResult(
        content=["golden"],
        structured_content={"record_ref": "record:golden", "found": True},
        meta={"fixture": "fastmcp.tool_result.v1"},
    )
    canonical = rfc8785.dumps(project_fastmcp_tool_result(result))
    assert "sha256:" + hashlib.sha256(canonical).hexdigest() == GOLDEN_PROJECTION_DIGEST


def test_freeze_binding_and_receipt_projection_agree():
    from fastmcp.tools.base import ToolResult

    result = ToolResult(
        content=["x"],
        structured_content={"k": "v"},
        meta=None,
    )
    projection = project_fastmcp_tool_result(result)
    via_binding = sha256_digest(projection)
    via_receipt = fastmcp_tool_result_digest(
        content=projection["content"],
        structured_content=projection["structuredContent"],
        meta=projection["_meta"],
        is_error=projection["isError"],
    )
    assert via_binding == via_receipt


# --------------------------------------------------------------------------- #
# FREEZE ITEM 12 — import and public API surfaces                             #
# --------------------------------------------------------------------------- #


def test_freeze_public_api_surface_matches_committed_snapshot():
    import importlib
    import pkgutil

    import dagr_mcp

    committed = _committed("public_api_surface.json")

    names = ["dagr_mcp"]
    for module_info in pkgutil.walk_packages(dagr_mcp.__path__, prefix="dagr_mcp."):
        names.append(module_info.name)
    live: dict[str, Any] = {}
    for name in sorted(names):
        module = importlib.import_module(name)
        all_ = getattr(module, "__all__", None)
        live[name] = sorted(all_) if all_ is not None else None
    assert live == committed["modules"]


def test_freeze_package_reexports_match_declared_allowlist():
    import types

    import dagr_mcp

    # DAGR-MCP-FREEZE-ACCEPT0: LEGIBILITY0 (1636cbc, "expose quickwrap at package
    # root") and LEGIBILITY1 (#50, e4a4f92, "expose explicit FastMCP construction
    # surface") deliberately re-export a small, explicit construction surface at
    # the package root. The frozen invariant is therefore NOT "submodules only"
    # but "top-level non-module names are EXACTLY dagr_mcp.__all__" — this still
    # fails closed on any UNINTENDED new re-export (a non-module name absent from
    # the declared allowlist), so the guard is preserved, not removed.
    reexported = {
        name
        for name in dir(dagr_mcp)
        if not name.startswith("_")
        and not isinstance(getattr(dagr_mcp, name), types.ModuleType)
    }
    assert reexported == set(dagr_mcp.__all__), (
        "package top-level re-exports drifted from the declared __all__ allowlist"
    )


def test_freeze_key_module_all_lists_are_exact():
    """Spot-freeze the public surface of the load-bearing binding modules."""

    committed = _committed("public_api_surface.json")["modules"]
    assert committed["dagr_mcp.fastmcp_binding"] == sorted(fastmcp_binding.__all__)
    assert committed["dagr_mcp.srs_receipts"] is None  # srs_receipts defines no __all__
    assert "project_fastmcp_tool_result" in fastmcp_binding.__all__
    assert "wrap_handler" in _committed("public_api_surface.json")["modules"][
        "dagr_mcp.enforcement_harness"
    ]


# --------------------------------------------------------------------------- #
# FREEZE ITEM 13 — unsupported or deliberately absent behavior                #
# --------------------------------------------------------------------------- #


def test_freeze_only_registered_binding_versions_are_accepted():
    assert srs_receipts.REGISTERED_BINDING_VERSIONS == frozenset(
        {"direct-harness.v0.1", "fastmcp.middleware.v0.1"}
    )


def test_freeze_unregistered_binding_version_is_refused(tmp_path):
    identity = freeze_identity()
    emitter = SignedReceiptEmitter(identity=identity, sink=RawEnvelopeFileSink(tmp_path))
    with pytest.raises(ReceiptContentError, match="unregistered binding_version"):
        emitter.emit_admission(
            context=ReceiptContext(
                runtime_instance_id="r", boundary_id="b", policy_pack_id="p",
                policy_pack_version="1", subject_ref="s", logical_call_id="c",
                actor_ref="a", binding_version="invented.binding.v9",
            ),
            requested_tool_name="records.lookup",
            argument_digest="sha256:" + "a" * 64,
            disposition="admitted",
        )
    assert not list(tmp_path.glob("urn_srs_receipt_*.json"))


def test_freeze_post_execution_failure_mode_is_single_valued():
    assert typing.get_args(fastmcp_binding.PostExecutionReceiptFailureMode) == (
        "alert_and_return_result",
    )
    config = fastmcp_binding.DAGRMiddlewareConfig(
        runtime_instance_id="r", boundary_id="b", policy_pack_id="p", policy_pack_version="1"
    )
    assert config.post_execution_receipt_failure == "alert_and_return_result"


def test_freeze_amnesiac_capability_unavailable_is_error_result_not_success():
    """Deliberately-absent native producer fails closed as an error result."""

    from dagr_mcp.amnesiac_fastmcp import _capability_unavailable_result

    result = _capability_unavailable_result("amnesiac.compile_context", "producer missing")
    assert result.is_error is True
    projection = project_fastmcp_tool_result(result)
    assert projection["isError"] is True
    assert projection["structuredContent"]["status"] == "capability_unavailable"
    # DAGRMiddleware would therefore classify this as error_returned, never result_returned.


def test_freeze_raw_content_keys_are_refused():
    with pytest.raises(ReceiptContentError, match="forbidden raw-content key"):
        srs_receipts.enforce_raw_content_exclusion(
            {"extensions": {"mcp": {"result": "leaked rows"}}}
        )


# --------------------------------------------------------------------------- #
# FREEZE ITEM 14 — ARCS verification of all emitted receipt classes           #
# --------------------------------------------------------------------------- #


@requires_arcs
def test_freeze_all_receipt_classes_pass_full_arcs_verification():
    identity = freeze_identity()
    bundle = identity.trust_bundle()
    expectations = _committed("arcs_expectations.json")
    assert expectations["profile"] == MCP_PROFILE

    committed_receipts = _committed_receipts()
    assert len(committed_receipts) == 8  # 3 admission + 5 outcome classes

    for entry in expectations["receipts"]:
        receipt = committed_receipts[entry["name"]]
        report = _arcs_verify_receipt(
            receipt, bundle, schema_path=SCHEMA_PATH, selected_profile=MCP_PROFILE
        ).to_dict()
        # The committed expectations are the frozen oracle for every verdict.
        for key, value in entry["verdicts"].items():
            assert report[key] == value, (entry["name"], key, report)
        assert report["passed"] == entry["passed"], entry["name"]
        assert report["failure_codes"] == entry["expected_failure_codes"], entry["name"]
        # Every emitted receipt class verifies clean under the frozen profile.
        assert report["passed"] is True, entry["name"]


@requires_arcs
def test_freeze_committed_expectations_are_internally_complete():
    expectations = _committed("arcs_expectations.json")
    names = {entry["name"] for entry in expectations["receipts"]}
    assert names == {
        "admission-admitted",
        "admission-refused",
        "admission-deferred",
        "outcome-result-returned",
        "outcome-error-returned",
        "outcome-exception",
        "outcome-task-submitted",
        "outcome-indeterminate",
    }


# --------------------------------------------------------------------------- #
# FREEZE ITEM 15 — re-signed non-Boolean governance-field rejection           #
# (arcs-verify merge da89ebe36f1e4d9921aeeb7ff12f377d6804e8f7)                 #
# --------------------------------------------------------------------------- #

SMUGGLED_RAW_RESULT = (
    "BEGIN tool transcript\n"
    "row 1: customer record balance 4210.55\n"
    "row 2: internal note — do not disclose to caller\n"
    "END transcript"
)


@requires_arcs
def test_freeze_resigned_non_boolean_delivery_field_is_rejected_by_arcs(tmp_path):
    """A genuinely re-signed receipt that swaps the delivery Boolean for raw
    material must be rejected on a *profile* (non-Boolean governance) ground, not
    merely on signature invalidity. This freezes the guard the arcs-verify merge
    da89ebe added, closing the A0 cross-repo gap."""

    identity = freeze_identity()
    emitter = SignedReceiptEmitter(identity=identity, sink=RawEnvelopeFileSink(tmp_path))
    receipt_id = emitter.emit_outcome(
        context=ReceiptContext(
            runtime_instance_id="r", boundary_id="b", policy_pack_id="p",
            policy_pack_version="1", subject_ref="s", logical_call_id="c",
            actor_ref="a", binding_version="fastmcp.middleware.v0.1",
        ),
        admission_receipt_ref="urn:srs:receipt:admission:1",
        outcome="indeterminate",
        additional_attestation_limits=(
            "The middleware is installed once at the institutional trust boundary; "
            "receipts attest only to observations at that boundary.",
        ),
        binding_owned_fields={
            "request_cancelled": True,
            "execution_state_unknown": True,
            "delivery_incomplete": True,
        },
    )
    receipt = next(
        json.loads(p.read_text())
        for p in tmp_path.glob("urn_srs_receipt_*.json")
        if json.loads(p.read_text())["receipt_id"] == receipt_id
    )

    forged = copy.deepcopy(receipt)
    forged["delivery_incomplete"] = SMUGGLED_RAW_RESULT
    forged.pop("receipt_signature", None)
    resigned = identity.sign_envelope(forged)
    assert resigned["delivery_incomplete"] == SMUGGLED_RAW_RESULT

    report = _arcs_verify_receipt(
        resigned, identity.trust_bundle(), schema_path=SCHEMA_PATH, selected_profile=MCP_PROFILE
    ).to_dict()

    # The re-sign is genuine: the signature is valid.
    assert report["signature_valid"] is True, report
    # Rejection is a profile-ground rejection, not signature invalidity.
    assert report["passed"] is False, report
    assert report["profile"] is False, report
    assert (
        "profile.non_boolean_governance_field:delivery_incomplete"
        in report["failure_codes"]
    ), report
